favicon: /favicon.ico


# Nav Menus
menu:
    Index: /
    Archives: /archives

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/vdorchan']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['GitHub', 'my awesome github', 'https://github.com/vdorchan']


# About
about_info:
    name: "vdorchan"
    bio: "折腾不止"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: blog-vdorchan
duoshuo: 

# Analytics
google_analytics: vdorchan
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
